### ISSUE TITLE
Error when dealing with absorbing material

### ISSUE THREAD

**Issue by matthew991033** [MLResearchAtOSRAM/tmm_fast#11]
When the substrate is an absorbing material, the calculation is correct. However, when it is placed at upper layer of the photonic structure with thickness large enough, for instance a structure like W(e. g. 1000 nm)/SiO2/W(substrate), the upper layer of W (Although this structure is meaningless) would lead to 'nan' in calculated reflectance.

**Comment by drcosquared** [comment]
I think I believe I know what the issue is. In the original tmm package, the coh_tmm function contains a check for very opaque layers, making them ever so slightly transparent to avoid nan situations:

` # For a very opaque layer, reset delta to avoid divide-by-0 and similar
    # errors. The criterion imag(delta) > 35 corresponds to single-pass
    # transmission < 1e-30 --- small enough that the exact value doesn't
    # matter.
    for i in range(1, num_layers-1):
        if delta[i].imag > 35:
            delta[i] = delta[i].real + 35j
            if 'opacity_warning' not in globals():
                global opacity_warning
                opacity_warning = True
                print("Warning: Layers that are almost perfectly opaque "
                      "are modified to be slightly transmissive, "
                      "allowing 1 photon in 10^30 to pass through. It's "
                      "for numerical stability. This warning will not "
                      "be shown again.")`

The tmm_fast method seems to have removed this check, not sure what the reason is. I may try to reimplement this check, but I'm not very familiar with pytorch.

**Comment by Nerrror** [comment]
Hey, thanks for bringing this to my attention. I reimplemented the opacity check but I'm not confident that this solves the issue here since It doesn't make sense that a thicker layer leads to the opacity problem since it would only make a difference is you give a very large k value to the solver. 
I could imagine though that when an absorbing layer becomes too large, the values in the transport matrix become too small which leads to nans when you're calculating the system matrix M. I correct that, too. Can you confirm whether the update solved the issue? 

@drcosquared would you mind sharing the thicknesses and refractive indices somehow if the update didn't resolve the problem?

**Comment by Nerrror** [comment]
I checked again and you were right, the opacitiy check was actually the key to getting the correct behaviour but I missunderstood what it was doing. Anyway, the original tmm and tmm_fast now have the same response. 
![image](https://github.com/MLResearchAtOSRAM/tmm_fast/assets/78930256/cff5e4f9-5fe3-42d5-be36-66a284fb1d3f)

**Comment by Nerrror** [comment]
I think I found the problem now. It was a combination of the opacity check and not enough floating point precision, I missunderstood what the opacity check was actually doing. Now, both programms give the same result again: 
![image](https://github.com/MLResearchAtOSRAM/tmm_fast/assets/78930256/47081631-ac88-451e-9884-f086f0e387fa)

Btw, I think you reversed the stacking order in your last graph, right?

**Comment by drcosquared** [comment]
@Nerrror thanks so much for your help! I've also confirmed that tmm_fast matches the original tmm package for my system.

I believe you're correct, I may have gotten the layers reversed in my last graph.
